apiVersion: v1
kind: Service
metadata:
  name: glimpse-service-user
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: glimpse-service-user
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glimpse-service-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glimpse-service-user
    spec:
      containers:
      - name: glimpse-service-user
        image: gcr.io/glimpse-123456/glimpse-service-user:latest
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_DATABASE_USER
            value: root
          - name: MYSQL_DATABASE_PASSWORD
            value: password
          - name: MYSQL_DATABASE_DB
            value: glimpse
          - name: MYSQL_DATABASE_HOST
            value: mysql
          - name: BUCKET_NAME
            value: glimpse-asset-old
          - name: HTTP_PORT
            value: "80"