apiVersion: v1
kind: Service
metadata:
  name: glimpse-service-user
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: glimpse-service-user
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glimpse-service-user
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: glimpse-service-user
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:5000",
          "-s", "glimpse-user-service.endpoints.glimpse-123456.cloud.goog",
          "-v", "2017-07-29r9",
        ]
        ports:
          - containerPort: 8081
      - name: echo
        image: gcr.io/glimpse-123456/glimpse-service-user:latest
        ports:
          - containerPort: 5000
